name = "AKSMP"
author = "minemobs"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e31e7aed61a7c7d6445055d735cd868d8ec878a3d50281a2ab230158b50a15e"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
