name = "AKSMP"
author = "minemobs"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9fa500266c6a820be82ff368f87efb5a0afa9a7404d308e49f6e245994001ac"

[versions]
forge = "10.13.4.1614-1.7.10"
minecraft = "1.7.10"
