name = "AKSMP"
author = "minemobs"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa96a5a4f26a5f699a51e2714df65cef752e6c0106ebb98013ae7e3ad5b7d95a"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
