name = "AKSMP"
author = "minemobs"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee275054f6768d4263806b375d2308dbab344bdb0db80ca82cc492bbc85b2018"

[versions]
forge = "10.13.4.1614-1.7.10"
minecraft = "1.7.10"
